force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Registration for a course</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>Registration-{0000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Models.cls
public class Models {
    public class Student {
        @AuraEnabled
        public Id id;
        @AuraEnabled
        public String name;

        public Student(Registration__c record) {
            this.id = record.Student__c;
            this.name = record.Student__r.Name;
        }

        public Student(Student__c record) {
            this.id = record.Id;
            this.name = record.Name;
        }
    }
}